NDefines.NMilitary.PARACHUTE_PENALTY_RANDOMNESS = 0.07
NDefines.NMilitary.PARADROP_PENALTY = -0.3
NDefines.NMilitary.PARADROP_HOURS = 24
NDefines.NMilitary.PARACHUTE_COMPLETE_ORG = 0.2
NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_DURATION = 60
NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_MULT = -0.6
NDefines.NAI.TRANSPORTS_PER_PARATROOPER = 15
NDefines.NCountry.PARADROP_AIR_SUPERIORITY_RATIO = 0.5